### Site metadata ###

title: Cheatsheets
description: A collection of code snippets and CLI notes for easy reference

github_username: MichaelCurrin

### Build settings ###

url: "https://michaelcurrin.github.io"
baseurl: "/cheatsheets"

theme: "minima"

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - vendor/
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Makefile
  - README.md
